CREATE TABLE `shain` (
  `SHAIN_NO` char(7) NOT NULL COMMENT '社員番号',
  `SHAIN_PW` varchar(20) NOT NULL COMMENT 'パスワード',
  `SHAIN_SEI` varchar(10) DEFAULT NULL COMMENT '社員名_性',
  `SHAIN_MEI` varchar(10) DEFAULT NULL COMMENT '社員名_名',
  `SHAIN_KANA_SEI` varchar(20) DEFAULT NULL COMMENT 'カナ_性',
  `SHAIN_KANA_MEI` varchar(20) DEFAULT NULL COMMENT 'カナ_名',
  `SHAIN_GENDER` char(1) DEFAULT NULL COMMENT '性別',
  `SHAIN_BIRTH` datetime DEFAULT NULL COMMENT '生年月日',
  `SHAIN_ADDRESS` varchar(20) DEFAULT NULL COMMENT '現住所(最寄駅)',
  `SHAIN_SCHOOL` char(1) DEFAULT NULL COMMENT '最終学歴',
  `UPDATE_DATETIME` datetime DEFAULT NULL COMMENT '更新日時',
  `UPDATE_NO` char(7) DEFAULT NULL COMMENT '更新者',
  `CREATE_DATETIME` datetime DEFAULT NULL COMMENT '新規作成日時',
  `CREATE_NO` char(7) DEFAULT NULL COMMENT '新規作成者',
  PRIMARY KEY (`SHAIN_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8